import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, headless: true, args: ['--enable-webgl', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.setDefaultTimeout(60000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:4173');
await page.waitForFunction(() => window.neonCoast?.snapshot().frames > 10);
await page.screenshot({ path: 'artifacts/desktop.png' });
const probe = await page.evaluate(() => window.neonCoast.canvasProbe());
assert.ok(probe.colors > 12, JSON.stringify(probe));
await page.locator('#pause').click();
await page.locator('#quality').selectOption('low');
await page.locator('#resume').click();
await page.locator('#start-mission').click();
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).mission.stage, 0);
const before = await page.evaluate(() => window.neonCoast.snapshot());
await page.keyboard.down('w');
await page.waitForFunction(z => window.neonCoast.snapshot().position.z < z - 12, before.position.z, { timeout: 60000 });
await page.keyboard.up('w');
const after = await page.evaluate(() => window.neonCoast.snapshot());
assert.ok(after.position.z < before.position.z - 10, JSON.stringify(after));
assert.ok(after.speed > 5);
await page.keyboard.press('Escape');
assert.equal(await page.locator('#menu').evaluate(e => e.open), true);
const paused = await page.evaluate(() => window.neonCoast.snapshot());
await page.waitForTimeout(300);
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).mission.time, paused.mission.time);
await page.locator('#resume').click();
await page.keyboard.down(' ');
await page.waitForFunction(() => Math.abs(window.neonCoast.snapshot().speed) < 2, null, { timeout: 60000 });
await page.keyboard.up(' ');
await page.keyboard.press('e');
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).driving, false);
await page.keyboard.press('e');
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).driving, true);
await page.keyboard.press('m');
assert.equal(await page.locator('#map-dialog').evaluate(e => e.open), true);
await page.screenshot({ path: 'artifacts/map.png' });
await page.locator('#close-map').click();
await page.locator('#recover-button').click();
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).mission, null);
await page.evaluate(() => localStorage.setItem('neon-coast-v1', JSON.stringify({ cash: 2700, completed: 2 })));
await page.reload();
await page.waitForFunction(() => window.neonCoast);
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).cash, 2700);
assert.equal(await page.locator('#mission-title').textContent(), 'Heat of the night');
await page.locator('#start-mission').click();
assert.equal((await page.evaluate(() => window.neonCoast.snapshot())).heat, 3);
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
mobile.on('pageerror', e => errors.push(e.message));
await mobile.goto('http://localhost:4173');
await mobile.waitForFunction(() => window.neonCoast?.snapshot().frames > 5);
assert.ok((await mobile.evaluate(() => window.neonCoast.canvasProbe())).colors > 12);
assert.equal(await mobile.locator('#mobile-controls').isVisible(), true);
await mobile.screenshot({ path: 'artifacts/mobile.png' });
const accel = mobile.locator('[data-key="w"]');
const accelBox = await accel.boundingBox();
await mobile.mouse.move(accelBox.x + accelBox.width / 2, accelBox.y + accelBox.height / 2);
await mobile.mouse.down();
await mobile.waitForFunction(() => window.neonCoast.snapshot().speed > 1, null, { timeout: 30000 });
await mobile.mouse.up();
assert.ok((await mobile.evaluate(() => window.neonCoast.snapshot())).speed > 0);
assert.deepEqual(errors, []);
console.log(JSON.stringify({ desktopCanvas: probe, movement: { before: before.position, after: after.position }, checks: ['render', 'drive', 'mission start', 'pause freezes mission', 'exit/enter', 'map', 'recovery cancels mission', 'saved progress', 'police pursuit', 'mobile rendering', 'touch throttle'], errors }, null, 2));
await browser.close();
