export const FLIPBOOK_LIMITS = { maxBytes: 50 * 1024 * 1024, maxPages: 40 };
export const FLIPBOOK_TEMPLATES = {
  studio: { name: 'Studio', background: '#111827', surface: '#ffffff', accent: '#f97316' },
  editorial: { name: 'Editorial', background: '#eee7dc', surface: '#fffdf8', accent: '#8b4513' },
  midnight: { name: 'Midnight', background: '#050816', surface: '#10182c', accent: '#7dd3fc' },
  meadow: { name: 'Meadow', background: '#e8f3eb', surface: '#ffffff', accent: '#237a57' },
  gallery: { name: 'Gallery', background: '#f4f4f5', surface: '#ffffff', accent: '#7c3aed' },
};
export function safeFlipbookTitle(value, fallback = 'My flipbook') {
  const cleaned = String(value || '').replace(/[<>\u0000-\u001F]/g, '').trim().replace(/\s+/g, ' ');
  return (cleaned || fallback).slice(0, 100);
}
export function safeHtmlFileName(title) {
  const slug = safeFlipbookTitle(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `${slug || 'flipbook'}.html`;
}
export function buildStandaloneFlipbook({ title, pages, template = 'studio', pageDuration = 650 }) {
  const theme = FLIPBOOK_TEMPLATES[template] || FLIPBOOK_TEMPLATES.studio;
  const safeTitle = safeFlipbookTitle(title);
  const encodedPages = JSON.stringify(pages).replace(/</g, '\\u003c');
  const encodedTitle = JSON.stringify(safeTitle).replace(/</g, '\\u003c');
  const duration = Math.min(1500, Math.max(200, Number(pageDuration) || 650));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeTitle.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</title><style>
*{box-sizing:border-box}body{margin:0;background:${theme.background};color:${theme.surface};font-family:system-ui,sans-serif}.app{min-height:100vh;display:grid;grid-template-rows:auto 1fr auto}.bar{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px 18px;background:#0008}.bar button{min-width:42px;min-height:38px;border:1px solid #ffffff30;border-radius:9px;background:#ffffff14;color:#fff}.title{font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stage{position:relative;display:grid;place-items:center;padding:24px 76px;overflow:hidden}.book{display:flex;justify-content:center;max-width:min(1100px,88vw);max-height:76vh;filter:drop-shadow(0 25px 35px #0008);transition:transform ${duration}ms cubic-bezier(.2,.8,.2,1),opacity ${duration}ms}.book.cover{max-width:min(560px,48vw)}.page{display:block;min-width:0;max-width:50%;max-height:76vh;object-fit:contain;background:${theme.surface}}.book.cover .page{max-width:100%}.book.turn{transform:perspective(1400px) rotateY(-8deg) scale(.985);opacity:.55}.side{position:absolute;top:50%;width:52px;height:68px;border:0;border-radius:12px;background:#0008;color:#fff;font-size:2.5rem;cursor:pointer;transform:translateY(-50%)}#prev{left:14px}#next{right:14px}.controls{display:flex;gap:14px;align-items:center;padding:15px 20px;background:#090909}.count{white-space:nowrap;font-weight:800}.track{height:5px;flex:1;overflow:hidden;border-radius:999px;background:#ffffff30}.track i{display:block;height:100%;background:${theme.accent};transition:width .3s}@media(max-width:600px){.stage{padding:10px 44px}.book{max-width:96vw}.book.cover{max-width:70vw}.page{max-height:70vh}.side{width:36px;height:54px;font-size:2rem}#prev{left:4px}#next{right:4px}}
</style><style>.stage:fullscreen{width:100vw;height:100vh;padding-bottom:72px}.side{-webkit-tap-highlight-color:transparent}@media(max-height:520px) and (orientation:landscape){.stage{padding-block:8px}.page{max-height:68vh}}@media(prefers-reduced-motion:reduce){.book,.track i{transition-duration:1ms!important}.book.turn{transform:none;opacity:1}}</style></head><body><main class="app"><header class="bar"><div class="title" id="title"></div><button onclick="document.documentElement.requestFullscreen?.()" aria-label="Fullscreen">⛶</button></header><section class="stage"><button class="side" id="prev" aria-label="Previous pages">‹</button><div class="book cover" id="book"><img class="page" id="left" alt=""><img class="page" id="right" alt="" hidden></div><button class="side" id="next" aria-label="Next pages">›</button></section><nav class="controls" aria-label="Page progress"><span class="count" id="count"></span><div class="track"><i id="progress"></i></div></nav></main><script>
const pages=${encodedPages},title=${encodedTitle},starts=[0,...Array.from({length:Math.ceil((pages.length-1)/2)},(_,n)=>1+n*2)];let position=0;const book=document.getElementById('book'),left=document.getElementById('left'),right=document.getElementById('right'),count=document.getElementById('count'),progress=document.getElementById('progress');document.getElementById('title').textContent=title;function show(next){if(!pages.length)return;position=(next+starts.length)%starts.length;const i=starts[position];book.classList.add('turn');setTimeout(()=>{left.src=pages[i];left.alt='Page '+(i+1);const hasRight=i>0&&Boolean(pages[i+1]);right.hidden=!hasRight;if(hasRight){right.src=pages[i+1];right.alt='Page '+(i+2)}book.classList.toggle('cover',i===0);count.textContent=(i===0?'1':(i+1)+' - '+Math.min(i+2,pages.length))+' / '+pages.length;progress.style.width=(Math.min(i+2,pages.length)/pages.length*100)+'%';book.classList.remove('turn')},${Math.round(duration / 3)})}document.getElementById('prev').onclick=()=>show(position-1);document.getElementById('next').onclick=()=>show(position+1);addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(position-1);if(e.key==='ArrowRight'||e.key===' ')show(position+1)});show(0);
let touchX=0,touchY=0;const stage=document.querySelector('.stage');stage.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY},{passive:true});stage.addEventListener('touchend',e=>{const x=e.changedTouches[0].clientX-touchX,y=e.changedTouches[0].clientY-touchY;if(Math.abs(x)>=48&&Math.abs(x)>Math.abs(y)*1.2)show(position+(x<0?1:-1))},{passive:true});
<\/script></body></html>`;
}
