import { SITE } from '@/lib/tools-config';
import Link from 'next/link';

import { generateAlternates } from '@/lib/seo';

export async function generateMetadata({ params }) {
  const { lang } = await params;
  return {
    title: `Terms of Service | ${SITE.name}`,
    description: `Terms of Service and usage guidelines for ${SITE.name}.`,
    alternates: generateAlternates(lang, '/terms'),
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-snippet': -1,
        'max-image-preview': 'large',
      },
    },
  };
}

export default async function TermsPage({ params }) {
  const { lang } = await params;
  const lp = (path) => lang === 'en' ? path : `/${lang}${path}`;

  return (
    <div className="container" style={{ padding: '80px 24px', maxWidth: '800px' }}>
      <h1 style={{ fontSize: '2.5rem', marginBottom: '24px', fontWeight: '800' }}>Terms of Service</h1>
      <p style={{ color: 'var(--text-muted)', marginBottom: '32px' }}>Last updated: {new Date().toLocaleDateString()}</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', color: 'var(--text-secondary)', lineHeight: '1.8' }}>
        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>1. Acceptance of Terms</h2>
          <p>
            By accessing and using {SITE.name}, you accept and agree to be bound by the terms and provision of this agreement. 
            If you do not agree to abide by these terms, please do not use this service.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>2. Description of Service</h2>
          <p>
            {SITE.name} provides a collection of free, browser-based text processing tools (the "Service"). 
            The Service is provided "as is" and "as available". We reserve the right to modify, suspend, or discontinue 
            the Service with or without notice at any time.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>3. Privacy and Data Security</h2>
          <p>
            Your privacy is extremely important to us. All text manipulation performed by our tools occurs entirely 
            within your web browser on your device. We do not transmit, store, or process your text data on our servers. 
            For more detailed information, please review our <Link href={lp('/privacy')} style={{ color: 'var(--brand-color)' }}>Privacy Policy</Link>.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>4. Acceptable Use</h2>
          <p>
            You agree to use the Service only for lawful purposes. While our tools process data locally and we cannot monitor 
            your usage, you agree not to use the Service to:
          </p>
          <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <li>Violate any local, state, national, or international law.</li>
            <li>Process or distribute malicious code, malware, or viruses.</li>
            <li>Attempt to interfere with or disrupt the normal operation of the website.</li>
            <li>Automate requests to the website in a way that places an unreasonable load on our infrastructure.</li>
          </ul>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>5. Intellectual Property</h2>
          <p>
            The website design, branding, and custom source code of {SITE.name} are owned by us. 
            However, you retain all rights to the text, data, and content you process using our tools. 
            We claim no ownership over your inputs or the resulting outputs.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>6. Disclaimer of Warranties</h2>
          <p>
            The Service is provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, 
            and hereby disclaim all other warranties, including without limitation, implied warranties or conditions of 
            merchantability, fitness for a particular purpose, or non-infringement of intellectual property.
          </p>
          <p style={{ marginTop: '8px' }}>
            While we strive for accuracy, we do not warrant that the outputs generated by our tools (including formatting, 
            calculations, cryptographic hashes, or conversions) will be entirely error-free.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>7. Limitation of Liability</h2>
          <p>
            In no event shall {SITE.name} or its operators be liable for any indirect, incidental, special, consequential 
            or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss 
            of data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to 
            access or use the Service.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '12px' }}>8. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at: <a href="mailto:Contact@ilovetexts.com" style={{ color: 'var(--brand-color)', fontWeight: '600' }}>Contact@ilovetexts.com</a>
          </p>
        </section>
      </div>
    </div>
  );
}
